name: Build and Test

on:
  pull_request:
  push:
  release:
    types:
      - created

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        os: [ubuntu-latest, windows-latest]
        include:
        - os: ubuntu-latest
          build_type: Debug
          config_flags: "-DUSE_ASAN=ON"
        - os: windows-latest
          build_type: Debug
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive
    - if: contains(matrix.os, 'ubuntu')
      name: Get Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends \
          p7zip-full build-essential zlib1g-dev libx11-dev \
          libusb-1.0-0-dev freeglut3-dev liblapacke-dev \
          libopenblas-dev libatlas-base-dev libpcap-dev \
          python3 python3-pip ninja-build libeigen3-dev
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Setup windows flags
      if: contains(matrix.os, 'windows') && matrix.build_type == 'Release'
      id: flags
      run: echo "SETUP_PY_FLAGS=-G 'Visual Studio 17 2022'" >> $GITHUB_OUTPUT
    - name: Get mac dependencies
      if: contains(matrix.os, 'macos')
      run: |
        brew install freeglut lapack libusb openblas
        brew info libusb
        brew ls libusb
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DUSE_EIGEN=On -DDOWNLOAD_EIGEN=On -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENABLE_TESTS=ON -DCMAKE_INSTALL_PREFIX=install_root ${{matrix.config_flags}}

    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE -v

    - name: Install
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE --target install

    - name: Set bundle name
      id: bundle
      run: echo "BUNDLE_FILE_NAME=libsurvive-$(git describe --tags)-${{ matrix.os }}.zip" >> $GITHUB_OUTPUT

    - name: Bundle
      if: matrix.build_type == 'Release'
      working-directory: ${{runner.workspace}}/libsurvive
      run: 7z a ${{runner.workspace}}/build/${{ steps.bundle.outputs.BUNDLE_FILE_NAME }} ${{runner.workspace}}/build/install_root/*

    - uses: actions/upload-artifact@v4
      name: Upload
      if: matrix.build_type == 'Release'
      with:
        name: libsurvive-${{ matrix.os }}-${{ matrix.build_type }}
        path: |
          ${{runner.workspace}}/build/${{steps.bundle.outputs.BUNDLE_FILE_NAME}}
          ${{runner.workspace}}/libsurvive/dist/*.whl

    - name: Test
      if: runner.os == 'Linux'
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE --output-on-failure --parallel
      env:
        LSAN_OPTIONS: suppressions=${{runner.workspace}}/libsurvive/useful_files/leak_suppressions.txt
